bot_token = "DISCORD BOT TOKEN GOES HERE"
DB_USER = 'root'
DB_PASS = ''
DB_HOST = 'localhost'
DB_DATABASE = "moolah"
vc_moolah = 10
vc_time = 60
msg_moolah = 5
time_between_msg_moolah = 300  # seconds
